AWSTemplateFormatVersion: "2010-09-09"
Description: AWS EC2 instance for Walacor

Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t3a.medium
    AllowedValues:
      - t3a.medium
      - m5a.large
    ConstraintDescription: must be a valid EC2 instance type.

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName

  S3BucketName:
    Description: S3 bucket name for Walacor
    Type: String

Resources:
  WalacorInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-0c55b159cbfafe1f0 # This should be the appropriate AMI ID for your region
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: WalacorInstance
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y aws-cli
          aws s3 cp s3://${S3BucketName}/walacor-config /etc/walacor/config

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Description: Instance Id of the newly created EC2 instance
    Value: !Ref WalacorInstance
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt WalacorInstance.PublicIp
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt WalacorInstance.AvailabilityZone
